const sqlite3 = require('sqlite3').verbose();
const path = require('path');

const dbPath = path.resolve(__dirname, '../server/database.sqlite');
const db = new sqlite3.Database(dbPath);

console.log('🧹 Starting Real-World Cleanup...');
console.log('ℹ️  Target DB:', dbPath);

db.serialize(() => {
    // 1. Truncate Transient Tables (Data that is generated by usage)
    const tablesToClear = [
        'lectures',
        'students',
        'attendance_records',
        'leave_requests',
        'notifications',
        'assignments',
        'submissions',
        'audit_logs'
    ];

    tablesToClear.forEach(table => {
        db.run(`DELETE FROM ${table}`, (err) => {
            if (err) console.error(`❌ Failed to clear ${table}:`, err.message);
            else console.log(`✅ Cleared ${table}`);
        });
        // Reset sequence (optional but good for "clean slate" feel)
        db.run(`DELETE FROM sqlite_sequence WHERE name='${table}'`);
    });

    // 2. Clear Teachers but KEEP Admin
    // Logic: Delete everyone who does NOT have department 'Admin' or 'Administration'
    const adminDepts = ['Admin', 'Administration'];
    const placeholders = adminDepts.map(() => '?').join(',');

    db.run(`DELETE FROM teachers WHERE department NOT IN (${placeholders})`, adminDepts, function (err) {
        if (err) console.error('❌ Failed to clear teachers:', err.message);
        else console.log(`✅ Cleared Teachers (Removed ${this.changes} non-admin accounts)`);
    });

    // 3. Log what remains
    db.get("SELECT COUNT(*) as count FROM teachers", (err, row) => {
        if (err) console.log("Error checking teachers:", err);
        else {
            console.log(`ℹ️  Teachers remaining: ${row.count} (Admins only)`);

            if (row.count === 0) {
                console.log('⚠️ No Admin found. Creating default System Admin...');
                try {
                    // Try to load bcrypt from server modules
                    const bcrypt = require(path.resolve(__dirname, '../server/node_modules/bcrypt'));
                    const hash = bcrypt.hashSync('admin123', 10);

                    db.run(`INSERT INTO teachers (name, email, password, department, post, is_hod, is_acting_hod) 
                            VALUES ('System Admin', 'admin@lecman.edu', '${hash}', 'Administration', 'Administrator', 0, 0)`,
                        (err) => {
                            if (err) console.error('❌ Failed to create default admin:', err.message);
                            else console.log('✅ Created default admin: admin@lecman.edu / admin123');
                        });
                } catch (e) {
                    console.error("Could not load bcrypt to create admin:", e.message);
                }
            }
        }
    });

    console.log('✨ Cleanup Complete. Database is ready for real use.');
});

db.close();
