// Error codes enumeration for consistent error handling
const ErrorCodes = {
    // Authentication & Authorization
    AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
    AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
    AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
    AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

    // Validation
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    VALIDATION_MISSING_FIELD: 'VALIDATION_MISSING_FIELD',
    VALIDATION_INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',
    VALIDATION_DUPLICATE: 'VALIDATION_DUPLICATE',

    // Database
    DB_CONNECTION_ERROR: 'DB_CONNECTION_ERROR',
    DB_QUERY_ERROR: 'DB_QUERY_ERROR',
    DB_NOT_FOUND: 'DB_NOT_FOUND',
    DB_CONSTRAINT_VIOLATION: 'DB_CONSTRAINT_VIOLATION',

    // Business Logic
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
    OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED',
    INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

    // File Operations
    FILE_UPLOAD_ERROR: 'FILE_UPLOAD_ERROR',
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',
    FILE_INVALID_TYPE: 'FILE_INVALID_TYPE',

    // Server
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

    // External Services
    EXTERNAL_API_ERROR: 'EXTERNAL_API_ERROR',
    EMAIL_SEND_ERROR: 'EMAIL_SEND_ERROR'
};

// HTTP status code mapping
const ErrorStatusCodes = {
    [ErrorCodes.AUTH_INVALID_CREDENTIALS]: 401,
    [ErrorCodes.AUTH_TOKEN_EXPIRED]: 401,
    [ErrorCodes.AUTH_TOKEN_INVALID]: 401,
    [ErrorCodes.AUTH_UNAUTHORIZED]: 401,
    [ErrorCodes.AUTH_FORBIDDEN]: 403,

    [ErrorCodes.VALIDATION_ERROR]: 400,
    [ErrorCodes.VALIDATION_MISSING_FIELD]: 400,
    [ErrorCodes.VALIDATION_INVALID_FORMAT]: 400,
    [ErrorCodes.VALIDATION_DUPLICATE]: 409,

    [ErrorCodes.DB_CONNECTION_ERROR]: 503,
    [ErrorCodes.DB_QUERY_ERROR]: 500,
    [ErrorCodes.DB_NOT_FOUND]: 404,
    [ErrorCodes.DB_CONSTRAINT_VIOLATION]: 409,

    [ErrorCodes.RESOURCE_NOT_FOUND]: 404,
    [ErrorCodes.RESOURCE_ALREADY_EXISTS]: 409,
    [ErrorCodes.OPERATION_NOT_ALLOWED]: 403,
    [ErrorCodes.INSUFFICIENT_PERMISSIONS]: 403,

    [ErrorCodes.FILE_UPLOAD_ERROR]: 500,
    [ErrorCodes.FILE_TOO_LARGE]: 413,
    [ErrorCodes.FILE_INVALID_TYPE]: 415,

    [ErrorCodes.INTERNAL_SERVER_ERROR]: 500,
    [ErrorCodes.SERVICE_UNAVAILABLE]: 503,
    [ErrorCodes.RATE_LIMIT_EXCEEDED]: 429,

    [ErrorCodes.EXTERNAL_API_ERROR]: 502,
    [ErrorCodes.EMAIL_SEND_ERROR]: 500
};

module.exports = {
    ErrorCodes,
    ErrorStatusCodes
};
